admin_rj_carrier_module:
  path: /rj-carrier/config
  methods: [GET]
  defaults:
    _controller: 'Roanja\Module\RjCarrier\Controller\Admin\RjCarrierModuleController::indexAction'
    _legacy_controller: AdminRjCarrierModule
    _legacy_link: 'AdminRjCarrierModule'

admin_rj_carrier_shipments:
  path: /rj-carrier/shipments
  methods: [GET]
  defaults:
    _controller: 'Roanja\Module\RjCarrier\Controller\Admin\ShipmentsController::indexAction'
    _legacy_controller: AdminRjShipments
    _legacy_link: 'AdminRjShipments'

